title: Charles 'CJ' Knoble
logo: /assets/img/Headshot 1.jpg
description: GIS Consultant, PhD Candidate <br> Montclair State University 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
