title: Charles 'CJ' Knoble
logo: /assets/img/Headshot 1.1.png
description: GIS Consultant, First-Generation Student <br> PhD Candidate, Montclair State University 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
