title: CJ, the EJ Guy
logo: /assets/img/Headshot 1.1.png
description: GIS and Data Science Consultant, <br> First-Generation Student
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
