title: Charles 'CJ' Knoble
logo: /assets/img/headshot - Copy.jpg
description: PhD Candidate <br> Montclair State University <br> [LinkedIn](https://www.linkedin.com/in/charles-knoble/)
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
