title: Charles 'CJ' Knoble, PhD
logo: /assets/img/Headshot 1.1.png
description: GIS and Data Science Consultant, First-Generation Student
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
