title: Charles 'CJ' Knoble
logo: /assets/img/headshot - Copy.jpg
description: PhD Candidate <br> Montclair State University <br> Email: cjknoble@gmail.com
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
